########################################################################################
#    		                   Script p_finalize.sh                                    #
#  Script to include identification (TITLE) on pMHCs and generate summary of D1-EM-D2  #
########################################################################################
#$1 > MHC allele
####
if [ $1 == "A0201" ]; then
	allele=HLA-A0201
fi
if [ $1 == "B2705" ]; then
	allele=HLA-B2705
fi
if [ $1 == "H2KB" ]; then
	allele=H2-Kb
fi
if [ $1 == "H2DB9" ] || [ $1 == "H2DB10" ]; then
    allele=H2-Db
fi
#Check for "FINAL" complex and create summary.txt
if [ -e FINAL-$1-pMHC.pdb ]
	then
		echo -e "\nProceeding with complex identification..."
        #Get epitope sequence from FINAL-*-pMHC.pdb
        echo -e "load FINAL-$1-pMHC.pdb" > get_seqC.pml
        echo -e "save seqC.fasta, chain C" >> get_seqC.pml
        pymol -c get_seqC.pml
        seq=$(sed -n "2p" seqC.fasta)
        #Save info on PDB header
        echo -e "TITLE     Complex generated by DockTope (Rigo et al., 2015)." > Title
        echo -e "TITLE     DockTope uses the D1-EM-D2 approach (Antunes et al., 2010)." >> Title
        echo -e "TITLE     This pMHC complex contains \"$seq\" in the context of $allele." >> Title
        cat Title FINAL-$1-pMHC.pdb > "$1"-"$seq"_pMHC.pdb
        rm ../EPITOPE.fasta FINAL-$1-pMHC.pdb get_seqC.pml seqC.fasta
        #
        #Generate summary.txt
        mv Title ../summary.txt        
        cd ../      #exit D2 folder
        sed -i 's/TITLE     //g' summary.txt
        sed -i '1s/^/--------------------------------------------------------------------\n/' summary.txt
        echo -e "--------------------------------------------------------------------" >> summary.txt
        #Get BE values from D1 and D2
        D1id=$(ls D1/TheOne/ | awk -F - '{print $1}' | awk -F _ '{print $3}')
        D2id=$(ls $1-D2/TheOne/ | awk -F - '{print $1}' | awk -F _ '{print $3}')
        BED1=$(grep "Dock $D1id:" D1/affinities.txt | awk -F : '{print $2}') 
        BED2=$(grep "Dock $D2id:" $1-D2/affinities.txt | awk -F : '{print $2}')
        #Add values to summary
        echo -e "\n> Docking 1" >> summary.txt
        echo -e "Conformation selected: vina_out_$D1id-ligand_1.pdb" >> summary.txt
        echo -e "Binding Energy: $BED1" >> summary.txt
        echo -e "\n> Energy Minimization" >> summary.txt
        grep "Potential Energy" EM_pMHC.log >> summary.txt
        echo -e "\n> Docking 2" >> summary.txt
        echo -e "Conformation selected: vina_out_$D2id-ligand_1.pdb" >> summary.txt
        echo -e "Binding Energy: $BED2" >> summary.txt
        echo -e "\nFinal complex saved as "$1"-"$seq"_pMHC.pdb" >> summary.txt
        #echo -e "--------------------------------------------------------------------" >> summary.txt
        cp $1-D2/"$1"-"$seq"_pMHC.pdb .       #Copy final complex to outside D2 folder
        tar -czvf DockTope_results.tar.gz *
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        echo -e "\n    All D1-EM-D2 tasks were successfully executed.                "
        echo -e "\n    Final pMHC complex renamed to "$1"-"$seq"_pMHC.pdb.      "
        echo -e "\n    Please check the file summary.txt for more details.           "
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
	else
		echo -e "\nWARNING: The PDB file with the final pMHC complex was not found!!"
		echo -e "\nWARNING: Aborting identification process..."
		exit
fi
