#########################################################################################
#		                Fit to Position template for Grasp2
#########################################################################################
#v4.1
##This PyMOL script has two porpouses:
##(i) generate a new pdb file from the one generated by editconf (which is not usable);
##(ii) fit this new pMHC over the Grasp2 template.
#
###USAGE
# pymol -c fit2grasp.py
#
from pymol.cgo import *
from pymol import cmd
#
#Load new pMHC complex
cmd.load ("pMHC_input.pdb")
#
#Load template for Grasp position
cmd.load ("/usr/local/bioscripts/biofiles/Template_Position_NewA0201_5R.pdb")
#
#Fit new pMHC over the template:
cmd.do ("align pMHC_input, Template_Position_NewA0201_5R")
#
#Save fitted pMHC into a new pdb file
cmd.save("pMHC_output.pdb", "pMHC_input", 0)
#


