########################################################################################
#      		                   Script prep2grasp v2.8.0    
########################################################################################
#Note: This script will use editconf (gromacs-4.6.3) at /usr/local/gromacs-Extra/bin
#
i=0
size=10
chains="ABCDEFGHIJKLMNOPRSTUVXYZABCDEFGHIJKLMNOPRSTUVXYZABCDEFGHIJKLMNOPRSTUVXYZABCDEFGHIJKLMNOPRSTUVXYZABCDEFGHIJKLMN0"
#Initialinzing user interface...
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e "\n                        \"prep2grasp v2.8\"                         "
echo -e "\n             Pipeline to prepare pMHCs for charges assessment"
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
#Confirming actions...
echo -e "\n NOTE: This script will list ALL PDB FILES in this folder. All PDB files"
echo -e "will be EDITED (change Chain ID and residues number). A backup folder is"
echo -e "also created to store the original files."
echo -e "\nAre you sure you want to proceed? (y/n)"; read question0         		
if [ $question0 = 'y' ] || [ $question0 = 'Y' ]
	then
		echo -e "\n>>>\nProceeding with editconf tasks...\n>>>\n"
	else
		echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
		echo -e "\n                  Thanks for using \"prep2grasp v2.8\"                 "
		echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
		exit
fi
#Creating a Log file...
echo -e "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" > Prep2grasp_LOG.txt
echo -e "          Report of the changes performed by prep2grasp:" >> Prep2grasp_LOG.txt
echo -e "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> Prep2grasp_LOG.txt
##
#NOTE:
#The idea was to use only one editconf command to generate the edited file, such as:
#editconf -f $filename -resnr 1 -label $label -o $fname-c$label.pdb
#However, the pdb generated by editconf is not usable (wrong format), and need to
#be edited once again with PyMOL. So I used this PyMol script (fit2grasp_X4.py).
#
#Sequence of commands in the first 3 lines of the following code:
#(1) Loop to cover all pdb files in the folder;
#(2) Comand to recover only the file name (whithout ".pdb");
#(3) Comand to assign a specific chain (from the string "chains") for each pdb file;
#
mkdir inputfiles
for filename in *.pdb ; do  #(1)
	fname=${filename%.*};   #(2)
	label=${chains:$i:1};   #(3)
	/usr/local/gromacs-Extra/bin/editconf -f $filename -resnr 1 -label $label -o pMHC_input.pdb
	pymol -c /usr/local/bioscripts/fit2grasp_X4.py  
	mv pMHC_output.pdb	$fname-c$label.pdb
	rm pMHC_input.pdb
    #Reporting operation to the Log file;
    echo -e "Chain \"$label\" was assigned for complex \"$fname\"" >> Prep2grasp_LOG.txt
	mv $filename inputfiles #Saving a backup;                                            
	i=$((i + 1))
	if [ $i == $size ];     #For each 10 structures, a new subfolder is created;
		then
            echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
			echo -e "\n         WARNING: Dataset is too large, it will be splited."
			echo -e "         Creating subfolder group_$size." 
            echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
			mkdir group_$size	
			mv *-c*.pdb group_$size
			size=$((size + 10))
		else 
			echo -e "\n>>> Writing file $fname-c$label.pdb\n" 	
            if [ $i == 111 ]; #The chains string has only 110 caracters,
                then          #if the folder cotains more then 110 caracters the script is aborted;
                    echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
			        echo -e "\nWARNING: The number of complexes exceeded the limit of this script."
			        echo -e "WARNING: Aborting prep2grasp immediately!" 
			        echo -e "WARNING: Remaining steps of the script will not be completed." 
			        echo -e "WARNING: This Folder will be rebooted for its original status."
			        echo -e "Note: Please try again with up to 110 PDB files in the folder" 
                    echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
                    rm -r group_*    #Files are recovered as the original situation of the folder;
                    cp inputfiles/* .
                    rm -r *c0.pdb Prep2grasp_LOG.txt inputfiles/
                    exit
            fi
 		
	fi
    finalcount=$i   #Recording the number of complexes edited;
done
#Checking for remaining files that were not placed in subfolders
if [ $finalcount == 10 ] || [ $finalcount == 20 ] || [ $finalcount == 30 ] || [ $finalcount == 40 ] || [ $finalcount == 50 ] || [ $finalcount == 60 ] || [ $finalcount == 70 ] || [ $finalcount == 80 ] || [ $finalcount == 90 ] || [ $finalcount == 100 ] || [ $finalcount == 110 ];
    then 
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        echo -e "           A total of $finalcount pMHCs received a new chain."
        echo -e "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
    else    
        mkdir group_$size
        for filename in *.pdb ; do
            mv $filename group_$size
        done
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        echo -e "           A total of $finalcount pMHCs received a new chain."
#        echo -e "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
fi
#
#Change of chains was completed...
#
#Prepare files for the analysis with Grasp2
#
echo -e "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
j=10
for groupname in group_* ; do
	echo -e "\n>>> Generating cluster for $groupname.\n"
    cd $groupname/
		cat *.pdb > NewpMHCs_cluster-$j.pdb	
		sed -i "s/ENDMDL/REMARK/g" NewpMHCs_cluster-$j.pdb
		sed -i "s/END/TER/g" NewpMHCs_cluster-$j.pdb
        mv NewpMHCs_cluster-$j.pdb ../
    cd ../
    j=$((j + 10))   
done
#Pymol tasks completed...
#Organizing files...
#rm group_*
mkdir editedfiles
mv group_* editedfiles
#
#Final addition to the LOG file:
echo -e "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n" >> Prep2grasp_LOG.txt
echo -e " A total of $finalcount pMHCs were edited and fitted into $((size/10)) cluster(s)." >> Prep2grasp_LOG.txt
echo -e "\n Note 1: Convert each cluster into a Grasp2 session file (*.tpr)." >> Prep2grasp_LOG.txt
echo -e " Note 2: Edit each \"tpr\" file to have the Grasp template coordinates." >> Prep2grasp_LOG.txt
echo -e " Note 3: Check the file \"Grasp_Template_coordinates.txt\"". >> Prep2grasp_LOG.txt
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> Prep2grasp_LOG.txt
echo -e "\n                  Thanks for using \"prep2grasp v2.8\"                 " >> Prep2grasp_LOG.txt
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n" >> Prep2grasp_LOG.txt
#
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
echo -e " PyMOL tasks were concluded."
echo -e " A total of $finalcount pMHCs were edited and fitted into $((size/10)) cluster(s)."
echo -e "\n Note: Check \"Prep2grasp_LOG.txt\" for a complete report".
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
###########Presenting divergent pathways...
echo -e "The following steps will depend on the option you choose."
echo -e "(1) Delphi + Grasp2;"
echo -e "(2) Delphi + Chimera;"
echo -e "(3) Abort;"
echo -e "\nEnter your option:"; read question1         		
if [ $question1 = '1' ] || [ $question1 = '2' ] #1stq1
	then
        if [ $question1 = '1' ] #2ndq1
            then
################Begin of Grap2 Pathway...
           		echo -e "\n>>>\nProceeding with \"Delphi + Grasp2\"...\n>>>"
                echo -e " Note 1: Convert each cluster into a Grasp2 session file (*.tpr)."
                echo -e " Note 2: Each \"tpr\" file must be edited to include template coordinates."
                echo -e "\nThis script can edit the coordinates if you have already the \"tpr\" files."
                echo -e "You want to proceed with coordinates editing? (y/n)"; read tpr         		
                if [ $tpr = 'y' ] || [ $tpr = 'Y' ]
	                then
		                echo -e "\n>>>\nProceeding with coordinates exchange...\n>>>"
						#Proceed with tpr editing
						l=10
						for graspfile in *.tpr ; do
							echo -e "\n>>> Editing coordinates for $graspfile.\n"
							#Writting 1st part of file
							sed -n '/^coordinates/,/^molecular_model/p' NewpMHCs_cluster-$l.tpr > $l-1st
							#Writting 3rd part of file
							sed -n '/^MM/,$p'  NewpMHCs_cluster-$l.tpr > $l-3rd
							#Cat with new middle part
							cat $l-1st /usr/local/bioscripts/biofiles/Grasp_Template_coordinates.txt $l-3rd > NewpMHCs_cluster-"$l"_fit.tpr
							#Organize files and upgrade the counter
							rm $l-1st $l-3rd NewpMHCs_cluster-$l.tpr 
							mv NewpMHCs_cluster-$l.pdb editedfiles
							l=$((l + 10))   
						done
	                else
		                #Copying file with Grasp coordinates...
		                cp /usr/local/bioscripts/biofiles/Grasp_Template_coordinates.txt .
                        echo -e "\n>>>\nSkipping coordinates editing...\n>>>"
                fi
				#Copying Grasp-A0201 ImajeJ Roiset
				cp /usr/local/bioscripts/biofiles/RoiSet_Grasp-A0201_7RCrystal.zip .
				cp /usr/local/bioscripts/biofiles/RoiSet_Grasp_2011-New.zip .
				#
############End of Grap2 Pathway...
            else # for the 2nd if of question1 (2ndq1)
################Begin of Chimera Pathway...
				mv NewpMHCs_cluster-*.pdb editedfiles
        		echo -e "\n>>>\nProceeding with \"Delphi + Chimera\"...\n>>>"
				#Running Delphi
				cp /usr/local/bioscripts/biofiles/default.crg .
				cp /usr/local/bioscripts/biofiles/default.siz .
				cp /usr/local/bioscripts/biofiles/delphi.param .
				mkdir Delphi
				for phifile in editedfiles/*/*.pdb ; do
					phiname=${phifile%.*};
					mv $phifile TARGET.pdb
					delphi delphi.param
					mv fort.20 $phiname.phi
					mv $phiname.phi Delphi
					mv TARGET.pdb $phifile
				done
				#Organizing files
				rm default.crg default.siz delphi.param ARCDAT
				cp /usr/local/bioscripts/biofiles/RoiSet_Chimera-A0201_7RCrystal.zip .
                cp /usr/local/bioscripts/biofiles/Template_Position_Chimera-A0201_7RCrystal.py .
                cp /usr/local/bioscripts/biofiles/Chimera_How-to-Proceed.txt .
				#
############End of Chimera Pathway...
        fi #Closing 2nd if of question1 (2ndq1)
    else
        echo -e "\nAborting script...\n"
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        echo -e "\n                  Thanks for using \"prep2grasp v2.8\"                 "
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
        exit
fi #Closing 1st if of question1 (1stq1)
#
###Initializing ASA assessment...
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e "\nProceed with ASA assessment? (y/n)"; read question_ASA 
if [ $question_ASA = 'y' ] || [ $question_ASA = 'Y' ]
	then
		echo -e "\n>>>\nProceeding with ASA assessment...\n>>>\n"
        cd inputfiles/
        echo -e "y" | p_asa
		mv * ../
		cd ..
		rm -r inputfiles/
	else
        echo -e "\nAborting script...\n"
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        echo -e "\n                  Thanks for using \"prep2grasp v2.8\"                 "
        echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
        exit
fi
#
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e "\n                  Thanks for using \"prep2grasp v2.8\"                 "
echo -e "\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NBLI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
